-- create db and use
USE `FORCE_DIRECTED_GRAPHS`;

-- drop all tables
SELECT concat('DROP TABLE IF EXISTS `', table_name, '`;')
FROM information_schema.tables
WHERE table_schema = 'FORCE_DIRECTED_GRAPHS';

-- create tables for nodes and edges
SET FOREIGN_KEY_CHECKS = 0;
SET FOREIGN_KEY_CHECKS = 1;
CREATE TABLE `VERT` (
	`ID` 		INT 	NOT NULL AUTO_INCREMENT,
	`COLOR` 	INT 	NOT NULL,
	`DEGREE`	INT 	NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `EDGE` (
	`SOURCE`	INT	NOT NULL,
	`TARGET` 	INT	NOT NULL,
	`WEIGHT` 	INT	NOT NULL,
	FOREIGN KEY (`SOURCE`) REFERENCES VERT(`ID`),
       	FOREIGN KEY (`TARGET`) REFERENCES VERT(`ID`)
);

CREATE TABLE `CLIQUE` (
	`ID`	 	INT 		NOT NULL AUTO_INCREMENT,
	`AMMO`	 	INT 		NOT NULL,
	`MEMBERS`	LONGTEXT	NOT NULL,
	CHECK (JSON_VALID(`MEMBERS`)),
	PRIMARY KEY (`ID`)
);
