-- create db and user
CREATE DATABASE FORCE_DIRECTED_GRAPHS;
USE FORCE_DIRECTED_GRAPHS;

CREATE USER 'mysql'@'localhost' IDENTIFIED BY 'mysql_password';
GRANT ALL ON FORCE_DRIECTED_GRAPHS.* TO 'mysql'@'localhost';
FLUSH PRIVILEGES;

-- create tables for nodes and edges
DROP TABLE IF EXISTS VERT;
CREATE TABLE VERT (
	ID 	INT 	NOT NULL AUTO_INCREMENT,
	COLOR 	INT 	NOT NULL,
	DEGREE 	INT 	NOT NULL,
	PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS EDGE;
CREATE TABLE EDGE (
	SOURCE 	INT	NOT NULL,
	TARGET 	INT	NOT NULL,
	WEIGHT 	INT	NOT NULL,
	FOREIGN KEY (SOURCE) REFERENCES VERT(ID),
       	FOREIGN KEY (TARGET) REFERENCES VERT(ID)
);

DROP TABLE IF EXISTS CLIQUE;
CREATE TABLE CLIQUE (
	ID 	INT 	NOT NULL AUTO_INCREMENT,
	AMMO 	INT 	NOT NULL,
	MEMBERS XML,
	PRIMARY KEY (ID)
);
